// Command gen-schema-record writes a record type's schema as Go source instead of
// discovering it with reflection at run time.
//
// Put a go:generate line next to the record type:
//
//	//go:generate go run github.com/aldok10/zdb/cmd/gen-schema-record -type Trade
//	type Trade struct {
//	    Datetime int64   `zdb:"datetime,time,unit=us"`
//	    Price    float64 `zdb:"price,price"`
//	    Size     uint64  `zdb:"size,index"`
//	}
//
// and the generated file gives every store of that type a schema with no
// reflection at all.
//
// # What it buys
//
// Without generation, record.SchemaOf walks the struct with reflect once per type
// and caches the result. That is already cheap — one walk, for the life of the
// process — so the honest summary is that generation moves a small cost out of
// the process entirely and buys two things that are not about speed:
//
//   - A schema that is wrong is a compile error rather than a runtime surprise.
//     The generated file spells every column out, so renaming a field or
//     mistyping a tag fails the build instead of producing a query language that
//     silently cannot select what it used to.
//   - No reflect in the binary. A caller who would rather not link reflect for a
//     record type can have a package with no reflect dependency at all.
//
// Neither is a performance argument, and the numbers say so: the reflected path
// is one cached lookup per type, so the difference shows up in startup and binary
// size, not in a query.
//
// # Why the offsets are unsafe.Offsetof and not numbers
//
// The generated code writes unsafe.Offsetof(Trade{}.Price) rather than a byte
// offset. That expression is a compile-time constant, so the compiler computes
// the layout and a generated schema cannot drift from the struct it describes —
// there is no number in the output for a field insertion to invalidate. It also
// means the generator never has to reproduce Go's alignment and padding rules,
// which is the one part of a struct layout a text tool gets subtly wrong.
//
// # What it does not do
//
// It does not replace validation. The generated code calls record.MustSchema,
// which enforces every rule SchemaOf enforces, so a generated schema is refused
// under exactly the conditions a reflected one is. What changes is when a
// mistake surfaces: the generator reports the same errors itself at generation
// time, and MustSchema is a backstop for a checked-in file someone hand-edited.
package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// zdbImportPath is the module path of the record package, the one dependency the
// generated file has.
const zdbImportPath = "github.com/aldok10/zdb/record"

// recordPkgName is the package clause of that import, which is what makes a
// `-qualify=record.` and an unaliased import the same thing.
const recordPkgName = "record"

// tagKey is the struct tag the generator reads. It is record.TagKey, repeated
// because the generator cannot import the record package's unexported constant
// without importing the package it is generating code for, and importing the
// package being generated is the one import that can be a cycle.
const tagKey = "zdb"

// genHeader marks a file as this generator's output. writeFile refuses to
// overwrite anything that does not carry it, so the generator cannot destroy a
// hand-written file that happens to share the name.
const genHeader = "// Code generated by gen-schema-record. DO NOT EDIT."

// config is the generator's settings, parsed once so a test can build one instead
// of mutating the flag package's process-wide state.
type config struct {
	typeName string
	output   string
	pkgName  string
	qualify  string
	dirs     []string
}

func main() {
	if err := run(os.Args[1:], &config{}, os.Stderr); err != nil {
		fmt.Fprintln(os.Stderr, "gen-schema-record:", err)
		os.Exit(1)
	}
}

// run parses args into cfg and generates. It takes a FlagSet rather than using
// the flag package's globals, because a test that calls this more than once would
// otherwise trip over a global that only accepts one Parse.
//
// The flag defaults live here rather than on config, which means the zero config
// is not a usable one: a caller that skips run gets an empty qualifier and
// generates unqualified names. That is deliberate. There is exactly one entry
// point that knows the defaults, and the tests use it rather than hand-building a
// config, so a new default cannot be set in one place and forgotten in another.
func run(args []string, cfg *config, stderr io.Writer) error {
	fs := flag.NewFlagSet("gen-schema-record", flag.ContinueOnError)
	fs.SetOutput(stderr)

	fs.StringVar(&cfg.typeName, "type", "", "record type to generate; default every tagged struct in the package")
	fs.StringVar(&cfg.output, "out", "", "output file; default <lowercase type>_schema_gen.go, or zdb_schema_gen.go when -type is omitted")
	fs.StringVar(&cfg.pkgName, "package", "", "package name; default the package of the source files")
	fs.StringVar(&cfg.qualify, "qualify", "record.", `prefix for record's identifiers, e.g. "record." or "" when generating inside the record package`)

	if err := fs.Parse(args); err != nil {
		return err
	}

	// An empty qualifier means "same package", which is what generating inside
	// record itself needs. Every emission writes qualify + "Name", so an empty
	// one needs no branch anywhere else.
	cfg.dirs = fs.Args()
	if len(cfg.dirs) == 0 {
		cfg.dirs = []string{"."}
	}

	return generate(cfg)
}

// generate is the whole pipeline: read the package, decide the columns, write the
// file. Every step returns an error rather than a warning, because go:generate
// stops the pipeline on a non-zero exit and a silently skipped regeneration is
// how a generated file starts drifting.
//
// It is reached through run, which fills in the defaults. A test that calls it
// directly has to say what the defaults are, which is the intended friction.
func generate(cfg *config) error {
	pkgName, files, err := parsePackage(cfg.dirs)
	if err != nil {
		return err
	}

	if cfg.pkgName != "" {
		pkgName = cfg.pkgName
	}

	sources, err := collect(files, cfg.typeName)
	if err != nil {
		return err
	}

	if len(sources) == 0 {
		if cfg.typeName != "" {
			return fmt.Errorf("no exported struct named %s carrying a %q tag", cfg.typeName, tagKey)
		}

		return fmt.Errorf("no exported struct in %s carries a %q tag, so there is nothing to generate",
			strings.Join(cfg.dirs, ", "), tagKey)
	}

	out := cfg.output
	if out == "" {
		if cfg.typeName != "" {
			out = strings.ToLower(cfg.typeName) + "_schema_gen.go"
		} else {
			out = "zdb_schema_gen.go"
		}
	}

	// A bare output name lands beside the sources rather than in the process's
	// working directory. go:generate runs with the package directory as cwd, so
	// the two are usually the same and this only matters when a caller passes -out
	// with an explicit source directory — which is every test here.
	if !filepath.IsAbs(out) && !strings.ContainsRune(out, filepath.Separator) {
		out = filepath.Join(cfg.dirs[0], out)
	}

	return writeFile(out, render(pkgName, cfg.qualify, sources))
}

// parsePackage reads every non-test, non-generated Go file in each directory.
//
// Both exclusions are load-bearing. A record type declared in a _test.go file is
// not something a store can be opened over, and a generated file declares no
// tagged struct of its own, so reading it back in would only mean a
// regeneration depends on the output of the previous one.
func parsePackage(dirs []string) (string, []*ast.File, error) {
	fset := token.NewFileSet()

	var (
		files   []*ast.File
		pkgName string
	)

	for _, dir := range dirs {
		entries, err := os.ReadDir(dir)
		if err != nil {
			return "", nil, fmt.Errorf("reading %s: %w", dir, err)
		}

		found := 0

		for _, e := range entries {
			name := e.Name()

			switch {
			case e.IsDir(),
				!strings.HasSuffix(name, ".go"),
				strings.HasSuffix(name, "_test.go"),
				strings.HasSuffix(name, "_schema_gen.go"):
				continue
			}

			f, err := parser.ParseFile(fset, filepath.Join(dir, name), nil, parser.SkipObjectResolution)
			if err != nil {
				return "", nil, fmt.Errorf("parsing %s: %w", name, err)
			}

			if pkgName == "" {
				pkgName = f.Name.Name
			} else if f.Name.Name != pkgName {
				return "", nil, fmt.Errorf("%s is package %s but %s is package %s; "+
					"generate one package at a time", name, f.Name.Name, dirs[0], pkgName)
			}

			files = append(files, f)
			found++
		}

		if found == 0 {
			return "", nil, fmt.Errorf("no Go source files in %s", dir)
		}
	}

	return pkgName, files, nil
}

// source is one struct's schema, in the form the generator will emit it.
type source struct {
	typeName string
	unit     string
	columns  []column
}

// column is what the generator decided about one field. It mirrors
// record.Column, except that Offset is an expression rather than a number.
type column struct {
	// owner is the struct this column belongs to, so the offset expression can
	// name it. It is redundant with source.typeName and carried anyway because a
	// column renders independently of its source.
	owner string
	// name is the ZQL spelling, field the Go name.
	name  string
	field string
	// goType is the field's Go type as the source writes it, used to emit a
	// compile-time guard that the field has not been retyped since generation.
	goType string
	offset string
	kind   string
	width  int
	time   bool
	price  bool

	primary bool
	indexed bool
	aliases []string
}

// collect finds every tagged struct and turns it into a source. A struct with no
// tags is not a record and is skipped rather than reported, because a package
// that holds one record type also holds every other struct in the file and an
// error for each would make the generator unusable there.
func collect(files []*ast.File, want string) ([]source, error) {
	var out []source

	for _, f := range files {
		for _, decl := range f.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				continue
			}

			for _, spec := range gd.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}

				// An alias cannot have field offsets of its own, so it is skipped
				// rather than resolved. The underlying type is what a store holds,
				// and it carries the tags.
				if ts.Assign.IsValid() {
					continue
				}

				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					continue
				}

				if want != "" && ts.Name.Name != want {
					continue
				}

				if !ts.Name.IsExported() {
					continue
				}

				src, err := collectStruct(ts.Name.Name, st)
				if err != nil {
					return nil, err
				}

				if src != nil {
					out = append(out, *src)
				}
			}
		}
	}

	return out, nil
}

// collectStruct builds one source, or returns nil when the struct carries no tag
// and so is not a record.
//
// The rules enforced here are record.SchemaOf's, in the same order, so a mistake
// is reported with the same wording whether it is found at generation time or at
// Open. Two implementations of one rule set is a duplication, and the alternative
// is running a reflection pass inside a tool that has no compiled package to
// reflect over; a golden test that generates and then checks the schema against
// record's own is what keeps them honest.
func collectStruct(name string, st *ast.StructType) (*source, error) {
	src := &source{typeName: name, unit: "UnitMilli"}

	seen := make(map[string]string)
	timeAt := -1

	for _, field := range st.Fields.List {
		tag, tagged := tagOf(field)

		// An embedded field has no name to make a column out of, and its promoted
		// fields have no offset expression this generator can write, so an
		// embedded struct is refused when tagged rather than silently flattened.
		if len(field.Names) == 0 {
			if tagged {
				return nil, fmt.Errorf("%s: an embedded field cannot be a column; "+
					"declare its fields explicitly", name)
			}

			continue
		}

		if !tagged {
			continue
		}

		for _, fname := range field.Names {
			// Unexported fields are skipped, matching record.SchemaOf: a column
			// naming one would be a schema whose Load faults, because the caller
			// holds a *T and cannot reach an unexported field through it.
			if !fname.IsExported() {
				continue
			}

			c, err := columnOf(name, fname.Name, field.Type, tag)
			if err != nil {
				return nil, fmt.Errorf("%s.%s: %w", name, fname.Name, err)
			}

			if err := claim(c, seen); err != nil {
				return nil, fmt.Errorf("%s.%s: %w", name, fname.Name, err)
			}

			if c.time {
				if timeAt >= 0 {
					return nil, fmt.Errorf("%s has two time columns, %s and %s",
						name, src.columns[timeAt].name, c.name)
				}

				timeAt = len(src.columns)
				src.unit = unitOf(tag)
			}

			src.columns = append(src.columns, c)
		}
	}

	if len(src.columns) == 0 {
		return nil, nil
	}

	if timeAt < 0 {
		return nil, fmt.Errorf("%s has no time column: tag exactly one field %q", name, "time")
	}

	if !isIntegerKind(src.columns[timeAt].kind) {
		return nil, fmt.Errorf("%s.%s is %s, a time column is an integer",
			name, src.columns[timeAt].name, src.columns[timeAt].kind)
	}

	return src, nil
}

// claim records the names a column took, so a later claim of the same name is
// refused naming the field that made the first.
func claim(c column, seen map[string]string) error {
	if c.name == "" {
		return errors.New("a tagged field needs a column name")
	}

	if err := validateName(c.name); err != nil {
		return err
	}

	if prev, dup := seen[c.name]; dup {
		return fmt.Errorf("column %q is already claimed by %s", c.name, prev)
	}

	seen[c.name] = c.field

	for _, a := range c.aliases {
		if err := validateName(a); err != nil {
			return err
		}

		if prev, dup := seen[a]; dup {
			return fmt.Errorf("alias %q is already claimed by %s", a, prev)
		}

		seen[a] = c.field
	}

	// Price is a fixed-point conversion, and a fixed-point conversion of an
	// integer is a worse integer, so it is refused here rather than accepted and
	// quietly ignored.
	if c.price && c.kind != "KindFloat64" {
		return fmt.Errorf("column %q is %s, price applies to a float64 column",
			c.name, goTypeName(c.kind))
	}

	// The header already stores the time column's bounds, so a min/max for it
	// would be a second copy that can never disagree with the first.
	if c.indexed && c.time {
		return fmt.Errorf("column %q is the time column, which is indexed by definition", c.name)
	}

	return nil
}

// columnOf turns one field into a column, parsing the tag the way
// record.parseTag does.
func columnOf(owner, field string, typ ast.Expr, tag string) (column, error) {
	kind, width, err := kindOfExpr(typ)
	if err != nil {
		return column{}, err
	}

	c := column{
		owner: owner,
		field: field,
		// goType is the field's type spelled the way the source spells it, kept
		// for the compile-time guard render emits. It is read from the AST rather
		// than derived from the Kind, because deriving it would be a second
		// mapping that could disagree with the first — and a disagreement here is
		// a guard that does not compile, or worse, one that compiles and guards
		// the wrong type.
		goType: exprString(typ),
		name:   field,
		offset: fmt.Sprintf("unsafe.Offsetof(%s{}.%s)", owner, field),
		kind:   kind,
		width:  width,
	}

	parts := strings.Split(tag, ",")

	// The first part is the name only when it is not an option. A tag of
	// `zdb:"price"` names no column, and reading it as a name while also setting
	// the price flag is the kind of ambiguity that costs an afternoon.
	if parts[0] != "" && !isOption(parts[0]) {
		c.name = parts[0]
		parts = parts[1:]
	}

	for _, o := range parts {
		switch {
		case o == "":
			return c, errors.New("empty option in tag")
		case o == "time":
			c.time = true
		case o == "price":
			c.price = true
		case o == "primary":
			c.primary = true
		case o == "index":
			c.indexed = true
		case strings.HasPrefix(o, "alias="):
			al, err := splitAliases(o[len("alias="):])
			if err != nil {
				return c, err
			}

			c.aliases = append(c.aliases, al...)
		case strings.HasPrefix(o, "unit="):
			// Read by unitOf, which is where a bad value is reported. It is not
			// an option the column carries.
		default:
			return c, fmt.Errorf("unknown tag option %q", o)
		}
	}

	return c, nil
}

// kindOfExpr maps a parsed type expression to a record.Kind constant name.
//
// This is a second implementation of record.KindOf and cannot avoid being one:
// the generator has an ast.Expr and no reflect.Type, because the package it is
// reading has not been compiled. The duplication is covered by
// TestGeneratorKindTableMatchesRecordKindOf, which asserts this table against
// record.KindOf for every type it accepts, so a divergence is a failing test
// rather than a schema that reads the wrong bytes at the wrong offset.
func kindOfExpr(e ast.Expr) (string, int, error) {
	switch t := e.(type) {
	case *ast.Ident:
		return identKind(t.Name)
	case *ast.ArrayType:
		return arrayKind(t)
	case *ast.StarExpr:
		return "", 0, fmt.Errorf("is a pointer to %s, a record is copied by value "+
			"and cannot hold a pointer", exprString(t.X))
	case *ast.SelectorExpr:
		// time.Time lands here, as does any qualified type. Both are refused, but
		// the message names the type so a caller who wrote time.Time is told what
		// to use instead by KindOf's own wording at run time; here the wording is
		// the general one because an AST cannot tell time.Time from any other.
		return "", 0, fmt.Errorf("is %s.%s, a column is an integer, a float, a bool or [N]byte",
			exprString(t.X), t.Sel.Name)
	case *ast.MapType:
		return "", 0, errors.New("is a map, which has no fixed width")
	case *ast.InterfaceType:
		return "", 0, errors.New("is an interface, which a record cannot hold")
	case *ast.FuncType:
		return "", 0, errors.New("is a func, which a record cannot hold")
	case *ast.ChanType:
		return "", 0, errors.New("is a channel, which a record cannot hold")
	case *ast.StructType:
		return "", 0, errors.New("is a struct, a column is a scalar or [N]byte")
	}

	return "", 0, fmt.Errorf("is %s, a column is an integer, a float, a bool or [N]byte",
		exprString(e))
}

// arrayKind handles [N]byte, the one fixed-width way to hold text.
func arrayKind(t *ast.ArrayType) (string, int, error) {
	if !isByteIdent(t.Elt) {
		// The length is not named because a slice-length array is rejected by the
		// slice case below, and the element type is what makes the message useful.
		return "", 0, fmt.Errorf("is an array of %s, a column array is [N]byte", exprString(t.Elt))
	}

	if t.Len == nil {
		return "", 0, errors.New("is a slice of byte, whose width is not known until " +
			"runtime: use [N]byte, or put the value in the shard key")
	}

	lit, ok := t.Len.(*ast.BasicLit)
	if !ok {
		return "", 0, fmt.Errorf("is an array whose length is %s rather than a literal, "+
			"so its width is not known at generation time", exprString(t.Len))
	}

	n, err := strconv.Atoi(lit.Value)
	if err != nil {
		return "", 0, fmt.Errorf("has an array length that is not a number: %s", lit.Value)
	}

	if n <= 0 {
		return "", 0, fmt.Errorf("has an array length of %d, which holds nothing", n)
	}

	return "KindBytes", n, nil
}

// identKind maps a bare type name to its record.Kind constant.
func identKind(name string) (string, int, error) {
	switch name {
	case "int64":
		return "KindInt64", 0, nil
	case "uint64":
		return "KindUint64", 0, nil
	case "int32":
		return "KindInt32", 0, nil
	case "uint32":
		return "KindUint32", 0, nil
	case "int16":
		return "KindInt16", 0, nil
	case "uint16":
		return "KindUint16", 0, nil
	case "int8":
		return "KindInt8", 0, nil
	case "uint8", "byte":
		return "KindUint8", 0, nil
	case "float64":
		return "KindFloat64", 0, nil
	case "float32":
		return "KindFloat32", 0, nil
	case "bool":
		return "KindBool", 0, nil
	case "string":
		return "", 0, errors.New("is a string, whose width is not known until " +
			"runtime: use [N]byte, or put the value in the shard key")
	}

	return "", 0, fmt.Errorf("is %s, a column is an integer, a float, a bool or [N]byte", name)
}

func isByteIdent(e ast.Expr) bool {
	id, ok := e.(*ast.Ident)

	return ok && (id.Name == "byte" || id.Name == "uint8")
}

// isIntegerKind mirrors record.Kind.integer.
func isIntegerKind(kind string) bool {
	switch kind {
	case "KindInt64", "KindUint64", "KindInt32", "KindUint32",
		"KindInt16", "KindUint16", "KindInt8", "KindUint8", "KindBool":
		return true
	}

	return false
}

// isOption mirrors record.isOption. The four bare option words are the whole set,
// with no synonyms, because the tag's first part shares a namespace with them.
func isOption(s string) bool {
	switch s {
	case "time", "price", "primary", "index":
		return true
	}

	return strings.HasPrefix(s, "alias=") || strings.HasPrefix(s, "unit=")
}

func splitAliases(s string) ([]string, error) {
	parts := strings.Split(s, "|")

	out := make([]string, 0, len(parts))

	for _, p := range parts {
		if p == "" {
			return nil, errors.New("empty column name in alias=")
		}

		out = append(out, p)
	}

	return out, nil
}

// unitOf reads the unit= option, defaulting to milliseconds.
//
// An unrecognised value becomes UnitUnknown rather than a default, which makes
// the generated code compile and the schema say so, instead of compiling to
// milliseconds and quietly misreading microsecond stamps as milliseconds.
func unitOf(tag string) string {
	_, rest, found := strings.Cut(tag, "unit=")
	if !found {
		return "UnitMilli"
	}

	if end := strings.IndexByte(rest, ','); end >= 0 {
		rest = rest[:end]
	}

	switch rest {
	case "ms", "milli", "millisecond", "milliseconds":
		return "UnitMilli"
	case "us", "micro", "microsecond", "microseconds":
		return "UnitMicro"
	case "ns", "nano", "nanosecond", "nanoseconds":
		return "UnitNano"
	}

	return "UnitUnknown"
}

// validateName refuses a name the ZQL lexer could not read back.
func validateName(n string) error {
	if n == "" {
		return errors.New("empty column name")
	}

	for i := range len(n) {
		if !isNameByte(n[i]) {
			return fmt.Errorf("column name %q may not contain %q", n, string(n[i]))
		}
	}

	return nil
}

// isNameByte is the query lexer's word rule. It is repeated because the generator
// cannot reach the lexer's unexported function, and a name the generator accepts
// but the lexer refuses is a column nobody can select.
func isNameByte(c byte) bool {
	return c == '_' || c == '.' ||
		(c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9')
}

// tagOf reads the zdb tag off a field by scanning the tag text.
//
// Not reflect.StructTag.Lookup, because StructTag is a parser for quoted key
// pairs and it fails on a tag this generator would otherwise accept. When the two
// disagree the struct is the source of truth, so the tag is read the simple way
// and any tag StructTag would choke on is left for the runtime to report.
func tagOf(f *ast.Field) (string, bool) {
	if f.Tag == nil {
		return "", false
	}

	raw := strings.Trim(f.Tag.Value, "`")

	needle := tagKey + ":\""

	i := strings.Index(raw, needle)
	if i < 0 {
		return "", false
	}

	rest := raw[i+len(needle):]

	end := strings.IndexByte(rest, '"')
	if end < 0 {
		// An unterminated tag cannot happen in a file that parses as Go, because
		// the backquote string would not have closed. Treated as tagged with
		// nothing after the colon so the option loop reports it.
		return "", true
	}

	return rest[:end], true
}

// exprString renders a type expression. It serves an error message that has to
// name what the caller wrote, and a generated compile-time type guard, which is
// why a BasicLit is rendered exactly rather than approximately.
func exprString(e ast.Expr) string {
	switch t := e.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.BasicLit:
		return t.Value
	case *ast.StarExpr:
		return "*" + exprString(t.X)
	case *ast.SelectorExpr:
		return exprString(t.X) + "." + t.Sel.Name
	case *ast.ArrayType:
		if t.Len == nil {
			return "[]" + exprString(t.Elt)
		}

		return "[" + exprString(t.Len) + "]" + exprString(t.Elt)
	case *ast.MapType:
		return "map[" + exprString(t.Key) + "]" + exprString(t.Value)
	case *ast.InterfaceType:
		return "interface"
	case *ast.FuncType:
		return "func"
	case *ast.ChanType:
		return "chan"
	case *ast.StructType:
		return "struct"
	}

	return "a type"
}

// goTypeName is the Go type a Kind constant maps to, for an error message that
// has to name the type rather than the constant.
func goTypeName(kind string) string {
	switch kind {
	case "KindInt64":
		return "int64"
	case "KindUint64":
		return "uint64"
	case "KindInt32":
		return "int32"
	case "KindUint32":
		return "uint32"
	case "KindInt16":
		return "int16"
	case "KindUint16":
		return "uint16"
	case "KindInt8":
		return "int8"
	case "KindUint8":
		return "uint8"
	case "KindFloat64":
		return "float64"
	case "KindFloat32":
		return "float32"
	case "KindBool":
		return "bool"
	case "KindBytes":
		return "bytes"
	}

	return "?"
}

// render writes the generated source.
//
// The output calls record.MustSchema rather than building a Schema literal,
// because the time column's index is derived and a literal would hardcode a count
// that adding a field would invalidate. MustSchema recomputes the index and
// re-runs every validation rule, so a generated schema is checked exactly as a
// reflected one is, and the generated file needs no knowledge of how a Schema is
// put together.
func render(pkg, qualify string, sources []source) []byte {
	var b bytes.Buffer

	b.WriteString(genHeader + "\n")
	b.WriteString("//\n")
	b.WriteString("// Regenerate with `go generate ./...`. The struct tags are the source of\n")
	b.WriteString("// truth: editing this file works until someone changes a tag, and then it\n")
	b.WriteString("// silently stops matching.\n\n")

	fmt.Fprintf(&b, "package %s\n\n", pkg)

	b.WriteString("import (\n\t\"unsafe\"\n")

	if alias := aliasFor(qualify); alias != "" {
		// The alias is written only when it differs from the package's own name,
		// because `record "…/record"` is the kind of redundancy a linter flags and
		// a reviewer stops reading past.
		if alias == recordPkgName {
			fmt.Fprintf(&b, "\n\t%q\n", zdbImportPath)
		} else {
			fmt.Fprintf(&b, "\n\t%s %q\n", alias, zdbImportPath)
		}
	}

	b.WriteString(")\n")

	for _, src := range sources {
		varName := unexported(src.typeName)

		fmt.Fprintf(&b, "\nvar %sSchema = %sMustSchema[%s](%q, %s%s, []%sColumn{\n",
			varName, qualify, src.typeName, src.typeName, qualify, src.unit, qualify)

		for _, c := range src.columns {
			renderColumn(&b, qualify, c)
		}

		b.WriteString("})\n")

		fmt.Fprintf(&b, `
// ZDBSchema returns %s's schema without reflection. %sSchemaOf finds this
// method by interface assertion, so opening a store of this type never walks the
// struct with reflect.
func (%s) ZDBSchema() *%sSchema[%s] {
	return %sSchema
}
`, src.typeName, qualify, src.typeName, qualify, src.typeName, varName)

		renderTypeGuards(&b, src)
	}

	out, err := format.Source(b.Bytes())
	if err != nil {
		// A format failure is a bug here, and returning the unformatted text with
		// a note beats writing nothing, because the unformatted text is what shows
		// what went wrong.
		b.Reset()
		b.WriteString("// gen-schema-record: the generated source did not parse and is shown\n")
		b.WriteString("// unformatted so the error is visible in the diff:\n")
		b.WriteString("//\n")
		b.Write(renderRaw(pkg, qualify, sources))

		return b.Bytes()
	}

	return out
}

// renderTypeGuards writes one `var _ T = Owner{}.Field` per column.
//
// These exist because unsafe.Offsetof is blind to the failure that matters most.
// It is a compile-time constant over the field's *position*, so renaming or
// removing a field breaks the build, but retyping one does not: changing
// `Price float64` to `Price int64` leaves the offset at 8, the generated file
// compiles, and a query then reads eight bytes of integer as a float64. Nothing
// in the build, and nothing in MustSchema, which validates the tag against the
// Kind it was generated with — both of which still say float64.
//
// The guard closes exactly that gap and nothing wider. A typed assignment
// compiles only if the field's type is identical, including the array length of a
// [N]byte column, so the one drift that cannot be caught at compile time is the
// one that is caught.
//
// It is a var and not a const because composite-literal field selection is not a
// constant expression in Go, and the cost is one byte per column at link time.
func renderTypeGuards(b *bytes.Buffer, src source) {
	if len(src.columns) == 0 {
		return
	}

	b.WriteString(`
// Compile-time guards. The offsets above catch a renamed or moved field; these
// catch a retyped one, which an offset alone would let through in silence.
var (
`)

	for _, c := range src.columns {
		fmt.Fprintf(b, "\t_ %s = %s{}.%s\n", c.goType, src.typeName, c.field)
	}

	b.WriteString(")\n")
}

// renderColumn writes one Column literal.
func renderColumn(b *bytes.Buffer, qualify string, c column) {
	fmt.Fprintf(b, "\t{Name: %q", c.name)

	if len(c.aliases) > 0 {
		quoted := make([]string, 0, len(c.aliases))
		for _, a := range c.aliases {
			quoted = append(quoted, strconv.Quote(a))
		}

		fmt.Fprintf(b, ", Aliases: []string{%s}", strings.Join(quoted, ", "))
	}

	fmt.Fprintf(b, ", Offset: %s, Kind: %s%s", c.offset, qualify, c.kind)

	if c.width > 0 {
		fmt.Fprintf(b, ", Width: %d", c.width)
	}

	for _, f := range []struct {
		on   bool
		name string
	}{
		{c.time, "Time"},
		{c.price, "Price"},
		{c.primary, "Primary"},
		{c.indexed, "Indexed"},
	} {
		if f.on {
			fmt.Fprintf(b, ", %s: true", f.name)
		}
	}

	b.WriteString("},\n")
}

// renderRaw is render without the format step, used only to show output that
// failed to parse.
func renderRaw(pkg, qualify string, sources []source) []byte {
	var b bytes.Buffer

	fmt.Fprintf(&b, "package %s\n\nvar _ = unsafe.Offsetof(struct{}{})\n\n", pkg)

	for _, src := range sources {
		fmt.Fprintf(&b, "var %sSchema = %sNewSchema[%s](%q, %s%s, nil)\n\n",
			unexported(src.typeName), qualify, src.typeName, src.typeName, qualify, src.unit)
	}

	return b.Bytes()
}

// aliasFor is the import alias for the record package, derived from the qualifier
// rather than hardcoded.
//
// The alias has to match the qualifier, because every emitted identifier is
// written as qualify + "Name" while the import decides what qualify resolves to.
// Deriving one from the other is what keeps `-qualify=zdb.` producing an import
// called zdb rather than one called record that nothing references. An empty
// qualifier means same-package generation, which needs no import at all.
func aliasFor(qualify string) string {
	return strings.TrimSuffix(qualify, ".")
}

// unexported lowercases a type name for a package-level variable, so the
// generated var does not collide with the type it describes and does not export a
// name the package never meant to export.
func unexported(s string) string {
	if s == "" {
		return "x"
	}

	return strings.ToLower(s[:1]) + s[1:]
}

// writeFile writes generated source, refusing to overwrite anything this
// generator did not write. A generator that clobbers a hand-written file is a
// generator that loses work.
func writeFile(path string, src []byte) error {
	if existing, err := os.ReadFile(path); err == nil {
		if !bytes.HasPrefix(existing, []byte(genHeader)) {
			return fmt.Errorf("%s exists and was not generated by gen-schema-record; "+
				"refusing to overwrite it", path)
		}
	}

	return os.WriteFile(path, src, 0o644)
}
