// Code generated by gen-schema-record. DO NOT EDIT.
//
// Regenerate with `go generate ./...`. The struct tags are the source of
// truth: editing this file works until someone changes a tag, and then it
// silently stops matching.

package record

import (
	"unsafe"
)

var barSchema = MustSchema[Bar]("Bar", UnitMilli, []Column{
	{Name: "datetime", Offset: unsafe.Offsetof(Bar{}.Datetime), Kind: KindInt64, Time: true},
	{Name: "open", Offset: unsafe.Offsetof(Bar{}.Open), Kind: KindFloat64, Price: true},
	{Name: "high", Offset: unsafe.Offsetof(Bar{}.High), Kind: KindFloat64, Price: true},
	{Name: "low", Offset: unsafe.Offsetof(Bar{}.Low), Kind: KindFloat64, Price: true},
	{Name: "close", Offset: unsafe.Offsetof(Bar{}.Close), Kind: KindFloat64, Price: true},
	{Name: "tick_volume", Offset: unsafe.Offsetof(Bar{}.TickVolume), Kind: KindUint64},
	{Name: "spread", Offset: unsafe.Offsetof(Bar{}.Spread), Kind: KindInt32},
	{Name: "volume", Offset: unsafe.Offsetof(Bar{}.Volume), Kind: KindUint64},
})

// ZDBSchema returns Bar's schema without reflection. SchemaOf finds this
// method by interface assertion, so opening a store of this type never walks the
// struct with reflect.
func (Bar) ZDBSchema() *Schema[Bar] {
	return barSchema
}

// Compile-time guards. The offsets above catch a renamed or moved field; these
// catch a retyped one, which an offset alone would let through in silence.
var (
	_ int64   = Bar{}.Datetime
	_ float64 = Bar{}.Open
	_ float64 = Bar{}.High
	_ float64 = Bar{}.Low
	_ float64 = Bar{}.Close
	_ uint64  = Bar{}.TickVolume
	_ int32   = Bar{}.Spread
	_ uint64  = Bar{}.Volume
)
