// Code generated by gen-schema-record. DO NOT EDIT.
//
// Regenerate with `go generate ./...`. The struct tags are the source of
// truth: editing this file works until someone changes a tag, and then it
// silently stops matching.

package record

import (
	"unsafe"
)

var tickSchema = MustSchema[Tick]("Tick", UnitMicro, []Column{
	{Name: "datetime", Offset: unsafe.Offsetof(Tick{}.Datetime), Kind: KindInt64, Time: true},
	{Name: "bid", Offset: unsafe.Offsetof(Tick{}.Bid), Kind: KindFloat64, Price: true},
	{Name: "ask", Offset: unsafe.Offsetof(Tick{}.Ask), Kind: KindFloat64, Price: true},
	{Name: "last", Offset: unsafe.Offsetof(Tick{}.Last), Kind: KindFloat64, Price: true},
	{Name: "volume", Offset: unsafe.Offsetof(Tick{}.Volume), Kind: KindUint64},
	{Name: "flags", Offset: unsafe.Offsetof(Tick{}.Flags), Kind: KindUint64},
	{Name: "volume_ext", Offset: unsafe.Offsetof(Tick{}.VolumeExt), Kind: KindUint64},
})

// ZDBSchema returns Tick's schema without reflection. SchemaOf finds this
// method by interface assertion, so opening a store of this type never walks the
// struct with reflect.
func (Tick) ZDBSchema() *Schema[Tick] {
	return tickSchema
}

// Compile-time guards. The offsets above catch a renamed or moved field; these
// catch a retyped one, which an offset alone would let through in silence.
var (
	_ int64   = Tick{}.Datetime
	_ float64 = Tick{}.Bid
	_ float64 = Tick{}.Ask
	_ float64 = Tick{}.Last
	_ uint64  = Tick{}.Volume
	_ uint64  = Tick{}.Flags
	_ uint64  = Tick{}.VolumeExt
)
